QEMS/Controllers/OperatorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QEMS.Models;

namespace QEMS.Controllers
{
    public class OperatorsController : Controller
    {
        private ApplicationDbContext db;
        public OperatorsController()
        {
            db = new ApplicationDbContext();
        }

        // GET: Operators
        public async Task<ActionResult> Index()
        {
            return View(await db.Operators.ToListAsync());
        }

        // GET: Operators/Details/5
        public async Task<ActionResult> Details()
        {
            var appid = StaticMethods.GetAppId();
            if (appid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Operator @operator = await db.Operators.Include(o=>o.ApplicationUser).FirstOrDefaultAsync(o=>o.ApplicationId == appid);
            if (@operator == null)
            {
                return HttpNotFound();
            }
            return View(@operator);
        }

        public async Task<ActionResult> DetailsById(int id)
        {
            
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Operator @operator = await db.Operators.Include(o => o.ApplicationUser).FirstOrDefaultAsync(o => o.OperatorId == id);
            if (@operator == null)
            {
                return HttpNotFound();
            }
            return View(@operator);
        }

        // GET: Operators/Create
        public ActionResult Create()
        {
            Operator @operator = new Operator();
            return View(@operator);
        }

        // POST: Operators/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "FirstName,LastName,Addresss,City,State,ZipCode")] Operator @operator)
        {
            if (ModelState.IsValid)
            {
                @operator.ApplicationId = StaticMethods.GetAppId();
                db.Operators.Add(@operator);
                await db.SaveChangesAsync();
                return RedirectToAction("LogOut", "Account");
            }

            return View(@operator);
        }

        // GET: Operators/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Operator @operator = await db.Operators.Include(o=>o.ApplicationUser).Where(o=>o.OperatorId == id).FirstOrDefaultAsync();
            if (@operator == null)
            {
                return HttpNotFound();
            }
            return View(@operator);
        }

        // POST: Operators/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Operator @operator, int id)
        {
            if (ModelState.IsValid)
            {
                @operator.ApplicationId = @operator.ApplicationUser.Id;
                var operatoredit = await db.Operators.Include(o => o.ApplicationUser).FirstOrDefaultAsync(o => o.OperatorId == id);
                operatoredit.ApplicationUser.UserName = @operator.ApplicationUser.UserName;
                operatoredit.ApplicationUser.Email = @operator.ApplicationUser.Email;
                operatoredit.FirstName = @operator.FirstName;
                operatoredit.LastName = @operator.LastName;
                operatoredit.Addresss = @operator.Addresss;
                operatoredit.City = @operator.City;
                operatoredit.State = @operator.State;
                operatoredit.ZipCode = @operator.ZipCode;

                db.SaveChanges();
                return RedirectToAction("Details");
            }
            return View(@operator);
        }

        // GET: Operators/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Operator @operator = await db.Operators.FindAsync(id);
            if (@operator == null)
            {
                return HttpNotFound();
            }
            return View(@operator);
        }

        // POST: Operators/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Operator @operator = await db.Operators.FindAsync(id);
            db.Operators.Remove(@operator);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QEMS/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QEMS.Models;

namespace QEMS.Controllers
{
    public class PeopleController : Controller
    {
        private ApplicationDbContext db;
        public PeopleController()
        {
            db = new ApplicationDbContext();
        }

        // GET: People
        public async Task<ActionResult> Index()
        {
            var people = db.People.Include(p => p.ApplicationUser);
            return View(await people.ToListAsync());
        }

        // GET: People/Details/5
        public async Task<ActionResult> Details()
        {
            var appid = StaticMethods.GetAppId();
            if (appid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = await db.People.Include(p=>p.ApplicationUser).FirstOrDefaultAsync(p=>p.ApplicationId == appid);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        public async Task<ActionResult> DetailsById(int id)
        {         
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = await db.People.Include(p => p.ApplicationUser).FirstOrDefaultAsync(p => p.PersonId == id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }
        // GET: People/Create
        public ActionResult Create()
        {
            //ViewBag.ApplicationId = new SelectList(db.Users, "Id", "Email");
            Person person = new Person();
            return View(person);
        }

        // POST: People/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "FirstName,MiddleName,LastName,DateOfBirth,PhoneNumber,Addresss,City,State,ZipCode,LicenseNumber")] Person person)
        {
            if (ModelState.IsValid)
            { 
                person.ApplicationId = StaticMethods.GetAppId(); ;
                db.People.Add(person);
                await db.SaveChangesAsync();
                return RedirectToAction("LogOut", "Account");
            }
            return View(person);
        }

        // GET: People/Edit/5
        public async Task<ActionResult> Edit(int? id)
        { 
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = await db.People.Include(p => p.ApplicationUser).Where(p => p.PersonId == id).FirstOrDefaultAsync();
            if (person == null)
            {
                return HttpNotFound();
            }
           
            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Person person, int id)
        {
            if (ModelState.IsValid)
            {
                person.ApplicationId = StaticMethods.GetAppId();               
                var personedit = await db.People.Include(p => p.ApplicationUser).Where(p => p.PersonId == id).FirstOrDefaultAsync();
                var user = personedit.ApplicationUser;
                personedit.ApplicationUser.UserName = person.ApplicationUser.UserName;
                personedit.ApplicationUser.Email = person.ApplicationUser.Email;
                personedit.FirstName = person.FirstName;
                personedit.MiddleName = person.MiddleName;
                personedit.LastName = person.LastName;
                personedit.PhoneNumber = person.PhoneNumber;
                personedit.DateOfBirth = person.DateOfBirth;
                personedit.Addresss = person.Addresss;
                personedit.City = person.City;
                personedit.State = person.State;
                personedit.ZipCode = person.ZipCode;
                personedit.LicenseNumber = person.LicenseNumber;
                db.SaveChanges();
                return RedirectToAction("Details");
            }
            return View(person);
        }

        // GET: People/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = await db.People.FindAsync(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Person person = await db.People.FindAsync(id);
            db.People.Remove(person);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QEMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @*@Styles.Render("~/Template/css/bootstrap/css")*@
    @Scripts.Render("~/bundles/modernizr")

			
</head>
<body>


    <div class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
        <div class="container" style="height:40px">
            <nav nav class="navbar navbar-expand-sm navbar-dark bg-dark" style="height:40px"  >
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    
                    <ul class="navbar-nav">
                        <li class="nav-item active navbar-brand font-weight-bolder text-uppercase ">@Html.ActionLink("QEMS", "Index", "Home") </li>

                       

                        @if (User.IsInRole("Admin") == true)
                        {
                            <li class="nav-item navbar-brand font-weight-bolder text-uppercase "> @Html.ActionLink(" Home ", "Index", "Home") </li>
                            <li class="nav-item navbar-brand font-weight-bolder text-uppercase "> @Html.ActionLink(" Situations + Operators ", "OperatorSituationsForAdmin", "Situations") </li>
                            <li class="nav-item navbar-brand font-weight-bolder text-uppercase "> @Html.ActionLink(" People ", "Index", "People") </li>
                            <li class="nav-item navbar-brand font-weight-bolder text-uppercase "> @Html.ActionLink(" Operators ", "Index", "Operators") </li>
                            <li class="nav-item navbar-brand font-weight-bolder text-uppercase "> @Html.ActionLink(" Situations ", "Index", "Situations") </li>
                            <li class="nav-item active navbar-brand navbar-brand font-weight-bolder text-uppercase "> @Html.ActionLink(" List of Kins ", "Index", "Kins") </li>
                        }
                        @if (User.IsInRole("Person") == true)
                        {
                            <li class="nav-item active navbar-brand font-weight-bolder text-uppercase"> @Html.ActionLink(" Home ", "Create", "Situations") </li>
                            <li class="nav-item active navbar-brand font-weight-bolder text-uppercase"> @Html.ActionLink(" Situations ", "PersonsSituations", "Situations") </li>
                            <li class="nav-item active navbar-brand font-weight-bolder text-uppercase "> @Html.ActionLink(" Profile ", "Details", "People") </li>
                            <li class="nav-item active navbar-brand font-weight-bolder text-uppercase"> @Html.ActionLink(" Kin ", "ListOfKinForThePersonToSee", "Kins") </li>
                        }
                        @if (User.IsInRole("Operator") == true)
                        {
                            <li class="nav-item active navbar-brand font-weight-bolder text-uppercase"> @Html.ActionLink(" Situations ", "Index", "Situations") </li>
                            <li class="nav-item active navbar-brand font-weight-bolder text-uppercase"> @Html.ActionLink(" Completed Situations ", "CompletedSituations", "Situations") </li>
                            <li class="nav-item active navbar-brand font-weight-bolder text-uppercase"> @Html.ActionLink(" Profile", "Details ", "Operators") </li>
                        }
                        <li class="nav-item active navbar-brand font-weight-bolder text-uppercase"> @Html.ActionLink(" About ", "About", "Home") </li>
                        <li class="nav-item active navbar-brand font-weight-bolder text-uppercase"> @Html.ActionLink(" Contact ", "Contact", "Home") </li>
                    </ul>
                    <span class="navbar-right">
                        @Html.Partial("_LoginPartial")
                    </span>

                </div>
            </nav>
        </div>
    </div>
    <hr>
   
    <div class="container body-content" id="myDIV"  style="background-color:darkslategrey">
<<<<<<< HEAD
=======
        <hr>
>>>>>>> ec8d25e7aeb6e4b9e78426b75cb9a41111210d88
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>